cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus={resources.cpus}
    --mem={resources.mem}
    --mail-user={resources.mailuser}
    --mail-type={resources.mailtype}

default-resources:
  - partition=long
  - cpus=10
  - mem=150GB
  - mailuser=klein.dylan@outlook.com
  - mailtype=ALL